### ISSUE TITLE
pg1350-DR Footprint Origin Off

### ISSUE THREAD

**Issue by Albert-IV** [crides/kleeb#2]
I was using the pg1350-R footprints until I decided to move to a matrix setup and updated them to use the pg1350-DR footprints.  When I did it, the keys all shifted up by approximately .25u.  I was able to update the footprint manually to fix this, but it might be good to fix this programmatically if you made it with a Python script.

Link to manually fixed footprint:
https://gist.github.com/Albert-IV/caa8f16e5f8a3b93db33d6508f415533

Before using pg1350-R footprints:
<img width="774" alt="Screen Shot 2022-11-19 at 6 17 49 PM" src="https://user-images.githubusercontent.com/1487206/202877415-faa511c9-d205-440a-bed0-e1764ae1b442.png">

After changing to pg1350-DR:
<img width="624" alt="Screen Shot 2022-11-19 at 6 17 55 PM" src="https://user-images.githubusercontent.com/1487206/202877419-0e8ea0d9-a4e9-44a2-beff-c34385043d6a.png">

**Comment by crides** [comment]
This is expected behavior, and noted in the README, though maybe not with enough importance:

> The center of the footprint is placed on the center of the diode to help with PCBA, 

And yes, [it's basically 0.25u](https://github.com/crides/kleeb/blob/698dc82c580452976f685637cedb0faee4ae114c/pg1350.py#L75)

**Comment by crides** [comment]
As for the solution, it's possible to have `D` variants with both shifted and unshifted origins easily, but it's the same amount of problem changing from the version where PCBA is not a concern to the one where it is.

Alternatively, we could have the origin fixed on the center of the diode regardless of the variant, but that would be a bit weird when using the non-`D` variants.

**Comment by Albert-IV** [comment]
As someone not familiar with PCBA, why does the origin matter on the footprint?  Personally I'd think that having the origin be the middle of the switch would be really important (at least for me).  This way swapping between footprints would be somewhat reliable between libraries.

**Comment by crides** [comment]
For PCBA you need to provide the center of the component to be assembled. Given that the diode is part of the switch footprint already, it'd make the most sense to use the switch itself for creating the position file.

**Comment by Albert-IV** [comment]
After I started working with the PCBA files I see what you mean.  I can close this for now.
